---
title: "Metabolome paper - Supplementary Figure 2"
author: "Viviana Freire"
date: "`r Sys.Date()`"
output: html_document
---

# Load libraries

```{r message=FALSE, warning=FALSE}
library(patchwork)
library(ggtext)
library(readxl)
library(tidyverse)
```

# Loading data

## MAG metadata

```{r}
metadata <- read_csv("input/metadata_matched_MAGs_data_11-29-21.csv")
```


## METABOLIC custom HMM table

```{r}
metabolic_files <- list.files('input/',
                              pattern = 'METABOLIC',
                              recursive = TRUE,
                              full.names = TRUE)

hab <- c('Bog', 'Fen', 'Palsa')

names(metabolic_files) <- hab

hmm_table <- imap(metabolic_files, function(x, y){
  df <- read_xlsx(x, sheet = 1) %>% 
    select(Category, Function, Gene.abbreviation, Gene.name, contains('Hmm.presence')) %>% 
    pivot_longer(contains('Hmm.presence'), names_to = 'genome', values_to = 'Presence') %>% 
    mutate(genome = str_remove(genome, 'X'),
           genome = str_remove(genome, '.Hmm.presence'),
           Habitat = y) %>% 
    filter(Presence == 'Present')
})
```

## Matching genomes

```{r}
micro_data <- map(str_to_lower(hab), function(x){
  file <- paste0('output/', x, '_sig_corr_taxa.csv')
  df <- read_csv(file) %>% 
    select(-any_of(c('Name', 'Habitat', 'Networked_bacteria'))) %>% 
    mutate(Habitat = str_to_title(x)) %>% 
    distinct()
})

micro_data_df <- do.call(rbind, micro_data) %>% 
  mutate(type = 'Bacterial abundance') %>% 
  select(cluster,
         var = Microbe,
         rho,
         pval_adj = p_adj,
         type,
         Habitat)

genome_belong <- micro_data_df %>% 
  select(var, Habitat) %>% 
  distinct() %>% 
  mutate(Habitat = factor(Habitat, levels = c('Palsa', 'Bog', 'Fen')))
```

## OTU table

```{r}
# Get list of annotated genomes

genomes <- hmm_table %>% 
  reduce(rbind) %>% 
  pull(genome) %>% 
  unique()

otu_table <- read_csv("input/otu_normalized_df_3-4-22.csv") %>% 
  filter(genome %in% genomes) %>% 
  select(genome, all_of(metadata$names_bnti), Phylum) %>% 
  pivot_longer(!c(genome, Phylum), names_to = 'sampleid', values_to = 'norm_abundance') %>% 
  left_join(metadata, by = c('sampleid' = 'names_bnti')) %>% 
  group_by(genome, Habitat, Phylum) %>% 
  summarise(summed_norm_abundance = sum(norm_abundance)) %>% 
  inner_join(genome_belong, by = c('genome' = 'var', 'Habitat')) %>% 
  mutate(Phylum = factor(Phylum)) %>% 
  ungroup() %>% 
  arrange(Phylum) %>% 
  mutate(order = n():1,
         Habitat = factor(Habitat, levels = c('Palsa', 'Bog', 'Fen')))
```

## BNTI files

```{r}
bnti_files <- list.files(path = 'input',
                         pattern = 'feature_microbe_tax',
                         recursive = TRUE,
                         full.names = TRUE)
names(bnti_files) <- hab

bnti <- imap(bnti_files, function(x, y){
  df <- read_csv(x) %>% 
    select(Member, Direction) %>% 
    mutate(Habitat = y)
})

bnti_df <- reduce(bnti, rbind)
```


# Plotting

# Plots colors

```{r}
phyl_colors <- ggpubr::get_palette('Paired', length(levels(otu_table$Phylum)))
names(phyl_colors) <- levels(otu_table$Phylum)
```


## Base plot

```{r}
hmm_table_df <- reduce(hmm_table, rbind) %>% 
  inner_join(otu_table, by = c('genome', 'Habitat')) %>% 
  inner_join(bnti_df, by = c('genome' = 'Member', 'Habitat')) %>% 
  mutate(Habitat = factor(Habitat, levels = c('Palsa', 'Bog', 'Fen')))

metabolic_annot_plot <- hmm_table_df %>% 
  filter(Category %in% c('Sulfur cycling', 'Nitrogen cycling', 
                         'Oxidative phosphorylation', 'Sulfur cycling enzymes (detailed)')) %>% 
  mutate(Presence = Category) %>% 
  ggplot() +
  geom_tile(aes(x = fct_reorder(genome, order),
                y = Gene.name),
            fill = 'gray30',
            color = 'white') +
  theme_bw() +
  facet_grid(rows = vars(Category),
             cols = vars(Habitat),
             scales = 'free',
             space = 'free') +
  scale_x_discrete(expand = c(0, 0)) +
  scale_y_discrete(expand = c(0, 0)) +
  theme(axis.title = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        strip.text.y = element_text(angle = 0),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())  

metabolic_annot_plot
```

## Abundance plot

```{r}
abun_for_metabolic <- hmm_table_df %>% 
  select(genome, order, summed_norm_abundance, Phylum, Habitat) %>% 
  distinct() %>% 
  ggplot() +
  geom_col(aes(x = fct_reorder(genome, order),
               y = summed_norm_abundance,
               fill = Phylum)) +
  facet_grid(cols = vars(Habitat),
             scales = 'free',
             space = 'free') +
  scale_fill_manual(values = phyl_colors) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_markdown(angle = 45, hjust = 1),
        strip.text = element_blank(),
        strip.background = element_blank(),
        axis.title = element_blank())
```

## Merging plot

```{r}
metabolic_annot_final <- (metabolic_annot_plot / abun_for_metabolic) +
  plot_layout(heights = c(2, .2), guides = 'collect')

metabolic_annot_final

ggsave('figures/Supplementary_fig_2.png', metabolic_annot_final, 
       dpi = 300, width = 18, height = 10)
```





